#!/bin/bash

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH

# setup vimrc for the way I like it
cp /assets/baseOS/vimrc /root/.vimrc
cp /assets/baseOS/curlc /root/.curlc

# copy repos into place
for repo in /assets/baseOS/repos/*.repo; do
	if [[ -f $repo ]]; then
		cp $repo /etc/yum.repos.d/
	fi
done

useradd -c 'Tyk service user' -m -s /sbin/nologin tyk

# make directories for the docker volumes
mkdir -m 750 -p /opt/tyk-plugins /opt/tyk-certificates
chown tyk:tyk /opt/tyk-plugins /opt/tyk-certificates
if grep -q 'release 7' /etc/redhat-release; then
	# centos 7
	yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm deltarpm
fi
if grep -q 'release 8' /etc/redhat-release; then
	# centos 8
	yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm deltarpm
fi

# skipping golang here because it's huge!
yum -y install procps-ng iputils net-tools.x86_64 vim-enhanced.x86_64 wget curl python3 jq # golang.x86_64
yum -y install python3-devel python3-setuptools
pip3 install --upgrade pip
pip3 install protobuf grpcio
if grep -q 'release 7' /etc/redhat-release; then
	# centos 7
	yum -y install jemalloc.x86_64 logrotate.x86_64 make.x86_64 openssl.x86_64 mongodb-org.x86_64 redis
fi
if grep -q 'release 8' /etc/redhat-release; then
	# centos 8
	yum -y install logrotate.x86_64 make.x86_64 openssl.x86_64 mongodb-org.x86_64 redis
fi

# open redis and mongo up to the world! Beware!!!
sed -i 's/bindIp/#bindIp/' /etc/mongod.conf
sed -i 's/^protected-mode yes/protected-mode no/' /etc/redis.conf
sed -i 's/^bind 127.0.0.1/#bind 127.0.0.1/' /etc/redis.conf

# tidyup to reduce the image size. Saves 200-300 MB
yum clean all
