#!/bin/bash

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH
SOURCE_DIR=$(dirname $(readlink -f $0))

# setup vimrc for the way I like it
cp $SOURCE_DIR/vimrc /root/.vimrc
cp $SOURCE_DIR/curlrc /root/.curlrc

# Disable fastestmirror because it sometimes selects a fast but incomplete mirror
if [[ -f /etc/yum/pluginconf.d/fastestmirror.conf ]]; then
	sed -i s/enabled=1/enabled=0/ /etc/yum/pluginconf.d/fastestmirror.conf
fi

# copy repos into place
for repo in $SOURCE_DIR/repos/*.repo; do
	if [[ -f $repo ]]; then
		cp $repo /etc/yum.repos.d/
	fi
done

useradd -c 'Tyk service user' -m -s /sbin/nologin tyk

# make directories for the docker volumes
mkdir -m 750 -p /opt/tyk-plugins /opt/tyk-certificates
chown tyk:tyk /opt/tyk-plugins /opt/tyk-certificates

# Release specitic steps
# centos 7 for gateway 2.x
if grep -q 'release 7' /etc/redhat-release; then
  # remove the mongo 5 repo
  rm /etc/yum.repos.d/mongodb-org-5.0.repo
	sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
	sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
	#yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm deltarpm
  yum -y install https://archives.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/e/epel-release-7-14.noarch.rpm deltarpm
  yum -y install procps-ng iputils net-tools vim-enhanced wget curl python3 jq diffutils # golang
fi

# centos 8 for gateway 3.x and 4.x
if grep -q 'release 8' /etc/redhat-release; then
  # remove the mongo 5 repo
  rm /etc/yum.repos.d/mongodb-org-5.0.repo
	sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
	sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
	yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm 
  yum -y install procps-ng iputils net-tools vim-enhanced wget curl python3 jq diffutils # golang
fi
# almalinux:9 for release 5
if grep -q 'release 9' /etc/redhat-release; then
  # remove the mongo 4.4 repo
  rm /etc/yum.repos.d/mongodb-org-4.4.repo
  sed -i 's/$releasever/8/' /etc/yum.repos.d/mongodb-org-5.0.repo
  yum -y install bash procps-ng iputils net-tools vim-enhanced wget python3 jq diffutils # golang
fi

# update all the OS packages
yum -y --disablerepo='tyk*' --disablerepo='mongo*' update

yum -y install python3-devel python3-setuptools
pip3 install --upgrade pip
pip3 install protobuf grpcio
if grep -q 'release 7' /etc/redhat-release; then
	# centos 7
	yum -y install jemalloc logrotate make openssl mongodb-org redis
fi
if grep -q 'release 8' /etc/redhat-release; then
	# centos 8
	yum -y install logrotate make openssl mongodb-org redis
fi
if grep -q 'release 9' /etc/redhat-release; then
	# almalinux:9
  yum -y install make openssl redis mongodb-org mongodb-mongosh git 
  ###################################
  # ksbctl sepecific setup
  cd /
  git clone https://github.com/ps258/tyk-scripts.git
  cd /tyk-scripts/python
  pip3 install -r requirements.txt
  mkdir /root/bin
  # end ksbctl sepecific setup
  ###################################
fi

# open mongo up to the world! Beware!!!
if [[ -f /etc/mongod.conf ]]; then
  sed -i 's/bindIp/#bindIp/' /etc/mongod.conf
  if ! grep -q fork /etc/mongod.conf; then
	  sed -i 's/processManagement:/processManagement:\n  fork: true/' /etc/mongod.conf
  fi
fi

# find the redis config file
if [[ -f /etc/redis.conf ]]; then
	REDIS_CONFIG=/etc/redis.conf
elif [[ -f /etc/redis/redis.conf ]]; then
	REDIS_CONFIG=/etc/redis/redis.conf
  ln -s /etc/redis/redis.conf /etc/redis.conf
else
	echo "[FATAL]Cannot find redis config file. Checked /etc/redis.conf and /etc/redis/redis.conf but didn't find them"
fi

# open redis up to the world! Beware!!!
if [[ ! -z $REDIS_CONFIG ]]; then
  sed -i 's/^protected-mode yes/protected-mode no/' $REDIS_CONFIG
  sed -i 's/^bind 127.0.0.1/#bind 127.0.0.1/' $REDIS_CONFIG
fi

# tidyup to reduce the image size. Saves 200-300 MB
# removed to speed up next stage
#yum clean all
