#!/bin/bash

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH
SOURCE_DIR=$(dirname $(readlink -f $0))

# setup vimrc for the way I like it
cp $SOURCE_DIR/vimrc /root/.vimrc
cp $SOURCE_DIR/curlrc /root/.curlrc

# copy repos into place
for repo in $SOURCE_DIR/repos/*.repo; do
	if [[ -f $repo ]]; then
		cp $repo /etc/yum.repos.d/
	fi
done
# Disable fastestmirror because it sometimes selects a fast but incomplete mirror
if [[ -f /etc/yum/pluginconf.d/fastestmirror.conf ]]; then
	sed -i s/enabled=1/enabled=0/ /etc/yum/pluginconf.d/fastestmirror.conf
fi

useradd -c 'Tyk service user' -m -s /sbin/nologin tyk

# make directories for the docker volumes
mkdir -m 750 -p /opt/tyk-plugins /opt/tyk-certificates
chown tyk:tyk /opt/tyk-plugins /opt/tyk-certificates
if grep -q 'release 7' /etc/redhat-release; then
	# centos 7
	yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm deltarpm
fi
if grep -q 'release 8' /etc/redhat-release; then
	# centos 8
	sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
	sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
	yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm 
fi

# skipping golang here because it's huge!
yum -y install procps-ng iputils net-tools vim-enhanced wget curl python3 jq diffutils # golang
yum -y install python3-devel python3-setuptools
pip3 install --upgrade pip
pip3 install protobuf grpcio
if grep -q 'release 7' /etc/redhat-release; then
	# centos 7
	yum -y install jemalloc logrotate make openssl mongodb-org redis
fi
if grep -q 'release 8' /etc/redhat-release; then
	# centos 8
	yum -y install logrotate make openssl mongodb-org redis
fi

# open mongo up to the world! Beware!!!
sed -i 's/bindIp/#bindIp/' /etc/mongod.conf
if ! grep -q fork /etc/mongod.conf; then
	sed -i 's/processManagement:/processManagement:\n  fork: true/' /etc/mongod.conf
fi

# find the redis config file
if [[ -f /etc/redis.conf ]]; then
	REDIS_CONFIG=/etc/redis.conf
elif [[ -f /etc/redis/redis.conf ]]; then
	REDIS_CONFIG=/etc/redis/redis.conf
else
	echo "[FATAL]Cannot find redis config file. Checked /etc/redis.conf and /etc/redis/redis.conf but didn't find them"
	exit 1
fi

# open redis up to the world! Beware!!!
sed -i 's/^protected-mode yes/protected-mode no/' $REDIS_CONFIG
sed -i 's/^bind 127.0.0.1/#bind 127.0.0.1/' $REDIS_CONFIG

# tidyup to reduce the image size. Saves 200-300 MB
# removed to speed up next stage
#yum clean all
