#!/bin/bash

# Script finds the admin auth token for a user and echos that.
# Any admin user will do.

PATH=/scripts:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH

for user in $(redis-cli --scan --pattern 'tyk-admin-api-*-*'); do
	if [[ "admin" == $(redis-cli get $user | jq .UserData.user_permissions.IsAdmin | xargs) ]]; then
		redis-cli get $user | jq .UserData.access_key | xargs echo
		exit 0
	fi
done
exit 1
