#!/bin/bash

# script to install the tyk components during the image build

PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

cd $(dirname $0)

# Install any dependency RPMs fro the 'deps' directory
dep_rpmlist=""
for rpm in deps/*.rpm 
do
	if [[ -f $rpm ]]
	then
		dep_rpmlist="$dep_rpmlist $rpm"
	fi
done
if [[ -n $dep_rpmlist ]]
then
	yum --disablerepo=* localinstall -y $dep_rpmlist
fi

# As of version 5.1 packages are not being build for EL7. But old versions are only available in the EL7 repo
# Since no single repo will do anymore and since EL8 packages are only made for 3.0.7-1 and later we'll use
# the EL7 repo for tyk <= version 4 and the EL8 repo for tyk >= 5
TYK_MAJOR_VERSION=$(echo $SBX_GATEWAY_VERS | cut -d- -f3 | cut -d. -f1)
if [[ $TYK_MAJOR_VERSION -gt 4 ]]; then
	sed -i 's/\/7\//\/8\//' /etc/yum.repos.d/tyk_tyk-*.repo
fi

# install tyk
# split out the tyk-sync install because it fails on M1 Macs causing the whole thing to fail
# Don't install the gateway in this step. Do that by itself so that we can try to install the ee version
if [[ -n $SBX_SYNC_VERS && "x86_64" == $(uname -i) ]]; then
	tyk_rpmlist="$SBX_DASHBOARD_VERS $SBX_PUMP_VERS $SBX_TIB_VERS $SBX_SYNC_VERS $SBX_EDP_VERS"
else
	tyk_rpmlist="$SBX_DASHBOARD_VERS $SBX_PUMP_VERS $SBX_TIB_VERS $SBX_EDP_VERS"
fi
for rpm in $tyk_rpmlist; do
  echo yum install --disablerepo=*-unstable -y $rpm
  yum --disablerepo=*-unstable -y install $rpm
done
# attempt to install the ee gateway so it's there if we need it
rpm=$(echo $SBX_GATEWAY_VERS | sed 's/gateway/gateway-ee/')
echo yum install --disablerepo=*-unstable -y $rpm
yum --disablerepo=*-unstable -y install $rpm
# if the ee version didn't install, just install the standard one
if [[ ! -d /opt/tyk-gateway ]]; then
	echo yum install --disablerepo=*-unstable -y $SBX_GATEWAY_VERS
  yum --disablerepo=*-unstable -y install $SBX_GATEWAY_VERS
fi

# attempt to install the ee version of the gateway
$echo yum install --disablerepo=*-unstable -y $rpm

# get the tyk.conf schema so 'tyk lint' works
if [[ -n $SBX_SCHEMA_URL ]]; then
	wget -q $SBX_SCHEMA_URL -O /assets/schema.json
fi
if [[ -s /assets/schema.json ]]
then
	mkdir -p /opt/tyk-gateway/cli/linter && \mv /assets/schema.json /opt/tyk-gateway/cli/linter
fi

# tidy up the yum repos to reduce the image size
yum clean all
