components: {}
info:
  title: httpbin
  version: Default
openapi: 3.0.6
paths: {}
x-tyk-api-gateway:
  info:
    name: httpbin
    state:
      active: true
  middleware:
    global:
      trafficLogs:
        enabled: true
  server:
    listenPath:
      strip: true
      value: /httpbin/
  upstream:
    url: http://httpbin.org/anything
