components: {}
info:
  title: httpbin
  version: Default
openapi: 3.0.6
paths: {}
x-tyk-api-gateway:
  info:
    dbId: 68f792231628e8000166f0ee
    id: 96456933a479435669d6b5fd331f8f24
    name: httpbin
    orgId: 68f792131628e8000166f0e0
    state:
      active: true
  middleware:
    global:
      trafficLogs:
        enabled: true
  server:
    listenPath:
      strip: true
      value: /httpbin/
  upstream:
    url: http://httpbin.org/anything
