#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

cp /assets/ubi/vimrc /root/.vimrc
cp /assets/ubi/mongodb-org-3.0.repo /etc/yum.repos.d/mongodb-org-3.0.repo

useradd -c 'Tyk service user' -m -s /sbin/nologin tyk
mkdir -m 750 -p /opt/tyk-plugins /opt/tyk-certificates
chown tyk:tyk /opt/tyk-plugins /opt/tyk-certificates
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install -y procps-ng iputils net-tools.x86_64 vim-enhanced.x86_64 wget curl python3 # golang.x86_64
pip3 install --upgrade pip
yum install -y jemalloc.x86_64 logrotate.x86_64 make.x86_64 openssl.x86_64 mongodb-org.x86_64 redis
