#!/bin/bash

PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

cd $(dirname $0)

dep_rpmlist=""
for rpm in deps/*.rpm 
do
	if [[ -f $rpm ]]
	then
		dep_rpmlist="$dep_rpmlist $rpm"
	fi
done
if [[ -n $dep_rpmlist ]]
then
	yum --disablerepo=* localinstall -y $dep_rpmlist
fi

tyk_rpmlist=""
for rpm in tyk/*
do
	if [[ -f $rpm ]]
	then
		tyk_rpmlist="$tyk_rpmlist $(basename $rpm)"
		rm -f $rpm
	fi
done
if [[ -n $tyk_rpmlist ]]
then
	echo "yum install -y $tyk_rpmlist"
	yum install -y $tyk_rpmlist
fi
if [[ -f /assets/schema.json ]]
then
	mkdir -p /opt/tyk-gateway/cli/linter && \mv /assets/schema.json /opt/tyk-gateway/cli/linter
elif [[ -f /assets/schema.json.default ]]
then
	mkdir -p /opt/tyk-gateway/cli/linter && cp /assets/schema.json.default /opt/tyk-gateway/cli/linter/
	ln -s /opt/tyk-gateway/cli/linter/schema.json.default /opt/tyk-gateway/cli/linter/schema.json
fi

yum clean all
